[package]
name = "bars-client"
version = "0.1.0"
authors = ["Patrick Winters <19wintersp@gmail.com>"]
edition.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true

[lib]
crate-type = ["staticlib"]

[build-dependencies]
cbindgen.workspace = true
