[workspace]
resolver = "2"
members = [
	"config/",
]

[workspace.package]
edition = "2021"
license = "MIT"
publish = false
repository = "https://github.com/19wintersp/bars"

[workspace.dependencies]
bincode = "1.3"
serde = "1.0"
