[workspace]
resolver = "2"
members = [
	"config/",
	"tool/confc/",
]

[workspace.package]
edition = "2021"
license = "MIT"
publish = false
repository = "https://github.com/19wintersp/bars"

[workspace.dependencies]
bars-config = { path = "config/" }
bincode = "1.3"
serde = "1.0"
