edition = "2021"

hard_tabs = true
hex_literal_case = "Lower"
match_block_trailing_comma = true
max_width = 80
newline_style = "Unix"
tab_spaces = 2
trailing_semicolon = false

ignore = [
	"/doc/",
	"/plugin/",
]
