[package]
name = "bars-protocol"
version = "0.1.0"
authors = ["Patrick Winters <19wintersp@gmail.com>"]
edition.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true

[dependencies]
serde = { workspace = true, features = ["derive"] }
