[package]
name = "bars-ipc"
version = "0.1.0"
authors = ["Patrick Winters <19wintersp@gmail.com>"]
edition.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true

[dependencies]
bars-config = { workspace = true, features = ["serde"] }
bars-graph = { workspace = true, features = ["serde"] }

postcard = { workspace = true, optional = true, features = ["use-std"] }
serde = { workspace = true, features = ["derive"] }
tokio = { workspace = true, optional = true, features = ["io-util", "net"] }

[features]
tcp = ["dep:postcard", "dep:tokio"]
