[package]
name = "bars-plugin-loader"
authors = ["Patrick Winters <19wintersp@gmail.com>"]
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true

[dependencies]
bars-euroscope.workspace = true
bars-platform.workspace = true
bars-tracing.workspace = true
bars-update.workspace = true

anyhow.workspace = true
libloading.workspace = true
tracing.workspace = true
windows = {
	workspace = true,
	features = ["Win32_Security", "Win32_System_Threading"],
}

[features]
download = [
	"bars-update/blocking",
	"bars-update/download",
	"windows/Win32_UI_WindowsAndMessaging",
]

[lib]
crate-type = ["cdylib"]
